### PR TITLE
Add defines for SPI_STATUS flags.

### PR DESCRIPTION
**Pull request by riggs**

### CODE REVIEW

**Comment by riggs** [comment]
This save space in my code because I want to keep a copy of the actual board config in memory. Doing so currently requires either creating a new array copied from `defaultRegisterResetState`, or modifying it directly. The array isn't referenced elsewhere in this repository.

I'll move the definitions over.

**Comment by trinamic-LH** [comment]
Do you want to keep track of the values in the chip at runtime? Because that is covered by the shadow register mechanism. It is currently not publically exposed via functions. What exactly are you trying to accomplish with your copy?

No, this is not an issue. It is autogenerated, but adding those SPI bits is something we will add to our code generator

**Comment by riggs** [comment]
I’m keeping the values in ram for easy access when tuning parameters during development. But I’m also modifying the defaults in the array before calling init to avoid sending configuration twice.

As I think about this more, your point about gcc leaving the original in rom makes me realize the emitted code is likely to be about the same, regardless of this change. I’ll reverse that commit.

**Comment by trinamic-LH** [comment]
If you have memory space issues one possible optimization would be to store (address, value) pairs instead of an entire array over the register address space with gaps. Something like that is done for the [shadow register constants](https://github.com/trinamic/TMC-API/blob/59c44a52fa82b7e7e2ea69812bfe0446c5adf8d4/tmc/ic/TMC5160/TMC5160.h#L82).
This changes the space requirement from 4 bytes/address * 128 addresses = 512 bytes to 8 bytes/used address * 61 used addresses = 488 Bytes. Note that you can reduce the 8 bytes/used address to 5 bytes/used address by eliminating the padding behind the 1-byte address value giving you 5*61=305 Bytes needed.

(We haven't implemented this due to readability concerns)

**Pull request merged**
